spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          # 匹配成功后，会被转发到8082端口，至于端口后面的path，会直接使用原始请求的
          # 例如http://127.0.0.1:8443/str，会被转发到http://127.0.0.1:12307/str
          uri: http://127.0.0.1:12307
          predicates:
            # 根据请求路径中带有"/hello/"，就算匹配成功
            - Path=/hello/**