server:
  port: 12308
spring:
  application:
    name: microServiceCloudUserCenter
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  nacos-user-service: http://ganghua-business #服务提供者的服务名