spring:
  profiles:
    active: dev
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      #password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 300

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/sc_gateway?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}

#jetcache:
#  statIntervalMinutes: 15
#  areaInCacheName: false
#  hidePackages: com.springboot.cloud
#  local:
#    # 默认永久本地缓存
#    default:
#      type: caffeine
#      keyConvertor: fastjson
#  remote:
#    # 默认永久的远程缓存
#    default:
#      type: redis
#      keyConvertor: fastjson
#      valueEncoder: kryo
#      valueDecoder: kryo
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${REDIS_HOST:localhost}
#      port: ${REDIS_PORT:6379}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

logging:
  level:
    xyz.ganghua.gateway: debug
    com.jalja.org.spring: debug
  file:
    path: logs/


#  application:
#    name: microServiceCloudGateway
#  cloud:
#    gateway: # 路由网关配置
#      routes:
#        # 将 user-cneter 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
#        - id: microServiceCloudUserCenter_routh #路由 id,没有固定规则，但唯一，建议与服务名对应
#          #          uri: http://localhost:12306 #匹配后提供服务的路由地址
#          uri: lb://microServiceCloudUserCenter
#          predicates:
#            # 以下是断言 必选全部符合条件
#            - Path=/usercenter/pament/**  #断言，路径匹配 注意：Path 中 P 为大写
#            - Method=GET #只能时 GET 请求时，才能访问
#
#        - id: microServiceCloudUserCenter_port_routh
#          uri: lb://microServiceCloudUserCenter
#          predicates:
#            - Path=/usercenter/**
#            - Method=GET
