spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
    lettuce:
      pool:
        max-active: 300

logging:
  level:
    com.springboot.cloud: debug
    com.jalja.org.spring: debug
  file:
    path: logs/
